openapi: 3.0.1
info:
  title: People API
  version: 1.0.0
paths:
  /people:
    get:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PeopleFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy
        passthroughBehavior: when_no_match
        requestParameters:
          integration.request.header.x-authemail: 'context.authorizer.authemail'
          integration.request.header.x-authuserid: 'context.authorizer.authuserid'
          integration.request.header.x-authroles: 'context.authorizer.authroles'
      responses:
        '200':
          description: 200 response
      security:
        - LambdaTokenAuthorizer: []
components:
  securitySchemes:
    LambdaTokenAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authorizer:
        type: request
        authorizerUri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerFunction.Arn}/invocations
        identitySource: method.request.header.Authorization
        authorizerResultTtlInSeconds: 300
